name: Deploy Frontend on AWS EC2

on:
  push:
    branches: ["fix/deploy-backend"]
    paths: ["frontend/**", ".github/workflows/deploy-frontend.yml"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: heig-edit/edit/frontend
  CONTAINER_NAME: frontend-container

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-tag: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for Docker image
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    needs: build-and-push-image
    runs-on: [ec2]
    steps:
      - name: Log in to the GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull image from GitHub Container Registry
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{needs.build-and-push-image.outputs.image-tag}}
      - name: Delete old container
        run: docker rm -f ${{ env.CONTAINER_NAME }}
      - name: Run new container
        run: docker run -d --restart=always -p 81:3000 --name ${{ env.CONTAINER_NAME }} --network host ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{needs.build-and-push-image.outputs.image-tag}}
      - name: Remove old image
        run: docker image prune -af
