name: Unit test frontend

on:
  workflow_dispatch:
  pull_request:
    types: [auto_merge_enabled]
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm ci
      - run: npm test
